# Generated by Django 3.0.5 on 2020-04-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_create_initial_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='quizzes',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='TakenQuiz',
        ),
    ]
