# Generated by Django 3.0.5 on 2020-04-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200401_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
    ]
