# Generated by Django 2.0.1 on 2018-01-18 18:07

from django.db import migrations


def create_grades(apps, schema_editor):
    Grade = apps.get_model('classroom', 'Grade')
    Grade.objects.create(grade_level='Pre-K', color='#ffc107')
    Grade.objects.create(grade_level='First', color='#343a40')
    Grade.objects.create(grade_level='Second', color='#007bff')
    Grade.objects.create(grade_level='Third', color='#28a745')
    Grade.objects.create(grade_level='Fourth', color='#17a2b8')
    Grade.objects.create(grade_level='Fifth', color='#16A085')
    Grade.objects.create(grade_level='Sixth', color='#DAF7A6')
    Grade.objects.create(grade_level='Seventh', color='#FFC300')
    Grade.objects.create(grade_level='Eigth', color='#FF5733')
    Grade.objects.create(grade_level='Ninth', color='#C70039')
    Grade.objects.create(grade_level='Tenth', color='#BA4A00')
    Grade.objects.create(grade_level='Eleventh', color='#900C3F')
    Grade.objects.create(grade_level='Twelfth', color='#BB8FCE')

class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_grade_color'),
    ]

    operations = [
        migrations.RunPython(create_grades),
    ]


