# Generated by Django 3.0.5 on 2020-04-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20200402_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='availability',
            name='color',
            field=models.CharField(default='#505050', max_length=7),
        ),
        migrations.AlterField(
            model_name='availability',
            name='time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='grade',
            name='color',
            field=models.CharField(default='#505050', max_length=7),
        ),
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#505050', max_length=7),
        ),
        migrations.AddField(
            model_name='student',
            name='sessions',
            field=models.ManyToManyField(related_name='session_students', to='classroom.Session'),
        ),
    ]
