# Generated by Django 3.0.5 on 2020-04-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='availability',
            field=models.ManyToManyField(related_name='available_teachers', to='classroom.Availability'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='grade_level',
            field=models.ManyToManyField(related_name='leveled_teachers', to='classroom.Grade'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='interests',
            field=models.ManyToManyField(related_name='interested_teachers', to='classroom.Subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sessions',
            field=models.ManyToManyField(related_name='session_teachers', to='classroom.Session'),
        ),
    ]
