# Generated by Django 3.0.5 on 2020-04-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20200403_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(related_name='interested_students', to='classroom.Subject', verbose_name='subjects'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='interests',
            field=models.ManyToManyField(related_name='interested_teachers', to='classroom.Subject', verbose_name='subjects'),
        ),
    ]
