# Generated by Django 3.0.5 on 2020-04-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_auto_20200403_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ManyToManyField(related_name='schooled_teachers', to='classroom.School'),
        ),
    ]
