# Generated by Django 3.0.5 on 2020-04-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20200403_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ManyToManyField(related_name='schooled_students', to='classroom.School'),
        ),
    ]
