# Generated by Django 3.0.5 on 2020-04-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_student_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
