# Generated by Django 3.0.5 on 2020-04-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_auto_20200403_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=50, null=True, verbose_name='your school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.CharField(max_length=50, null=True, verbose_name='your school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='distance',
            field=models.ManyToManyField(related_name='distanced_teachers', to='classroom.Distance', verbose_name='max lesson radius'),
        ),
    ]
