# Generated by Django 3.0.5 on 2020-04-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_auto_20200408_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='zoom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
