# Generated by Django 3.0.5 on 2020-04-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_quiz_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='zoom',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
