# Generated by Django 3.0.5 on 2020-04-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_auto_20200410_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='zoom',
            field=models.URLField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
