# Generated by Django 3.0.5 on 2020-04-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_auto_20200410_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='zoom',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
