# Generated by Django 3.0.5 on 2020-04-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0021_auto_20200413_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rate',
            field=models.IntegerField(default='15', max_length=50, verbose_name='your asking rate (in $/hour'),
        ),
    ]
