# Generated by Django 3.0.5 on 2020-04-15 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0023_auto_20200414_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='owner',
            new_name='tutor',
        ),
    ]
