# Generated by Django 3.0.5 on 2020-04-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0026_auto_20200416_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='material',
            field=models.TextField(null=True, verbose_name='Material Covered'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(null=True, verbose_name='Lesson Date (mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Student Username'),
        ),
    ]
