# Generated by Django 3.0.5 on 2020-04-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0029_auto_20200416_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='material',
            field=models.TextField(null=True, verbose_name='Zoom Link + Meeting Details'),
        ),
    ]
