# Generated by Django 3.0.5 on 2020-04-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0030_auto_20200418_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rate',
            field=models.FloatField(default='15', max_length=50, verbose_name='your asking rate (in $/hour'),
        ),
    ]
