# Generated by Django 3.0.5 on 2020-05-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0031_auto_20200421_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='rate',
            field=models.FloatField(default=22.5, max_length=30, verbose_name='Lesson Rate'),
        ),
    ]
